# Utiliza una imagen de Nginx como base
FROM nginx

# Copia el archivo de configuración del reverse proxy al contenedor
COPY nginx.conf /etc/nginx/nginx.conf

# Expone el puerto 80 para que podamos acceder al reverse proxy
EXPOSE 80
